export type Ability = "Сила" | "Ловкость" | "Телосложение" | "Интеллект" | "Мудрость" | "Харизма";

export type SkillActionDef = {
  slug: string;
  ru: string;
  en: string;
  trained?: boolean;
  cost?: string;
  traits?: string[];
  desc: string;
  dc?: string;
};

export type SkillDef = {
  slug: string;
  ru: string;
  en: string;
  ability: Ability;
  desc: string;
  actions: SkillActionDef[];
};

export type DcRow = { label: string; dc: number };
export type DcAdjust = { label: string; mod: number };
export type LevelDc = { level: number; dc: number };

export const SIMPLE_DCS: DcRow[] = [
  { label: "Нетренированный", dc: 10 },
  { label: "Тренированный", dc: 15 },
  { label: "Эксперт", dc: 20 },
  { label: "Мастер", dc: 30 },
  { label: "Легендарный", dc: 40 },
];

export const DC_ADJUSTMENTS: DcAdjust[] = [
  { label: "Невероятно лёгкое", mod: -10 },
  { label: "Очень лёгкое", mod: -5 },
  { label: "Лёгкое", mod: -2 },
  { label: "Сложное", mod: +2 },
  { label: "Очень сложное", mod: +5 },
  { label: "Невероятно сложное", mod: +10 },
];

export const RARITY_ADJUSTMENTS: DcAdjust[] = [
  { label: "Обычное", mod: 0 },
  { label: "Необычное", mod: +2 },
  { label: "Редкое", mod: +5 },
  { label: "Уникальное", mod: +10 },
];

export const LEVEL_DCS: LevelDc[] = [
  { level: 0, dc: 14 },
  { level: 1, dc: 15 },
  { level: 2, dc: 16 },
  { level: 3, dc: 18 },
  { level: 4, dc: 19 },
  { level: 5, dc: 20 },
  { level: 6, dc: 22 },
  { level: 7, dc: 23 },
  { level: 8, dc: 24 },
  { level: 9, dc: 26 },
  { level: 10, dc: 27 },
  { level: 11, dc: 28 },
  { level: 12, dc: 30 },
  { level: 13, dc: 31 },
  { level: 14, dc: 32 },
  { level: 15, dc: 34 },
  { level: 16, dc: 35 },
  { level: 17, dc: 36 },
  { level: 18, dc: 38 },
  { level: 19, dc: 39 },
  { level: 20, dc: 40 },
  { level: 21, dc: 42 },
  { level: 22, dc: 44 },
  { level: 23, dc: 46 },
  { level: 24, dc: 48 },
  { level: 25, dc: 50 },
];

// --- общие действия, повторяющиеся в нескольких навыках ---

const RECALL_KNOWLEDGE = (topic: string): SkillActionDef => ({
  slug: "recall-knowledge",
  ru: "Вспомнить знание",
  en: "Recall Knowledge",
  cost: "1 действие",
  traits: ["concentrate", "secret"],
  desc: `Вспомнить факт про ${topic}. Провал даёт неточную или обманчивую информацию (ведущий бросает скрытно).`,
  dc: "DC по уровню темы (Level DC). Необычное +2, редкое +5, уникальное +10.",
});

const DECIPHER_WRITING = (scope: string): SkillActionDef => ({
  slug: "decipher-writing",
  ru: "Расшифровать письмена",
  en: "Decipher Writing",
  trained: true,
  cost: "исследование",
  traits: ["concentrate", "secret"],
  desc: `Разобрать ${scope} текст: шифр, древний язык, эзотерические пометки.`,
  dc: "Level DC текста; сложные/старые шифры — +2…+5 (сложное/очень сложное).",
});

const IDENTIFY_MAGIC = (scope: string): SkillActionDef => ({
  slug: "identify-magic",
  ru: "Определить магию",
  en: "Identify Magic",
  trained: true,
  cost: "10 минут",
  traits: ["concentrate", "secret"],
  desc: `Понять природу ${scope} эффекта или предмета: школа, назначение, активация, проклятия.`,
  dc: "Level DC предмета/эффекта. Проклятия и артефакты часто «сложное» (+2) или «очень сложное» (+5).",
});

const LEARN_A_SPELL = (tradition: string): SkillActionDef => ({
  slug: "learn-a-spell",
  ru: "Изучить заклинание",
  en: "Learn a Spell",
  trained: true,
  cost: "1 час за ранг",
  traits: ["concentrate"],
  desc: `Добавить ${tradition} заклинание в свой репертуар/книгу. Нужен доступ к заклинанию и расходники (см. таблицу).`,
  dc: "DC = Level DC ранга заклинания. Провал — нельзя учить заново, пока не получишь уровень.",
});

const EARN_INCOME: SkillActionDef = {
  slug: "earn-income",
  ru: "Заработать",
  en: "Earn Income",
  trained: true,
  cost: "простой (дни)",
  traits: ["downtime"],
  desc: "Работа по профилю в даунтайме: ремесло, выступление, знание. Заработок зависит от сложности задачи и результата.",
  dc: "DC уровня задачи (Level DC). Сумма монет — по таблице Earn Income для уровня задачи.",
};

// --- навыки ---

export const SKILLS: SkillDef[] = [
  {
    slug: "acrobatics",
    ru: "Акробатика",
    en: "Acrobatics",
    ability: "Ловкость",
    desc: "Равновесие, уклонение, манёвры в пространстве. Уклоняться от хватов и лазать узостями.",
    actions: [
      {
        slug: "balance",
        ru: "Баланс",
        en: "Balance",
        cost: "1 действие",
        traits: ["move"],
        desc: "Пройти по узкой/скользкой/шаткой поверхности. Провал — падаешь ниц или скользишь; критпровал — падаешь.",
        dc: "DC поверхности. Узкая 15, очень узкая 20, обледенелая +2…+5.",
      },
      {
        slug: "maneuver-in-flight",
        ru: "Манёвр в полёте",
        en: "Maneuver in Flight",
        trained: true,
        cost: "1 действие",
        traits: ["move"],
        desc: "Сложный воздушный манёвр: резкий разворот, пикирование, висение при шторме.",
        dc: "DC манёвра по ситуации. Обычный — Level DC; ураган — очень сложное (+5).",
      },
      {
        slug: "squeeze",
        ru: "Протискивание",
        en: "Squeeze",
        trained: true,
        cost: "исследование",
        traits: ["move"],
        desc: "Пролезть через узкий проход (5 футов в минуту при успехе, 10 при критуспехе).",
        dc: "Узкая щель DC 15; очень узкая DC 30. На провале — застрял или -5 футов/мин.",
      },
      {
        slug: "tumble-through",
        ru: "Кувырок сквозь",
        en: "Tumble Through",
        cost: "1 действие",
        traits: ["move"],
        desc: "Пройти сквозь клетку врага (не считая её сложной). При провале — проход останавливается.",
        dc: "КЗ Рефлексов противника.",
      },
    ],
  },
  {
    slug: "arcana",
    ru: "Магия",
    en: "Arcana",
    ability: "Интеллект",
    desc: "Тайные (arcane) знания: заклинания, артефакты, плоскости, магические существа.",
    actions: [
      RECALL_KNOWLEDGE("магию, тайные традиции, магических существ"),
      {
        slug: "borrow-arcane-spell",
        ru: "Одолжить тайное заклинание",
        en: "Borrow an Arcane Spell",
        trained: true,
        cost: "подготовка",
        desc: "Подготовить заклинание из чужой книги заклинаний (только для книжных колдунов).",
        dc: "Level DC ранга заклинания. Провал — слот уходит впустую.",
      },
      DECIPHER_WRITING("магический или зашифрованный"),
      IDENTIFY_MAGIC("тайного"),
      LEARN_A_SPELL("тайное"),
    ],
  },
  {
    slug: "athletics",
    ru: "Атлетика",
    en: "Athletics",
    ability: "Сила",
    desc: "Физические подвиги: лазанье, прыжки, плавание, силовые манёвры в бою.",
    actions: [
      {
        slug: "climb",
        ru: "Лазанье",
        en: "Climb",
        cost: "1 действие",
        traits: ["move"],
        desc: "Подняться на 5 футов (10 при критуспехе). Провал — стоишь; критпровал — падаешь.",
        dc: "Верёвка со стеной 10; шершавая скала 15; гладкая стена 20; потолок/без выступов 30.",
      },
      {
        slug: "disarm",
        ru: "Обезоруживание",
        en: "Disarm",
        trained: true,
        cost: "1 действие",
        traits: ["attack"],
        desc: "Выбить оружие/предмет. Успех — -2 цели к атакам этим оружием до конца её хода; критуспех — роняет.",
        dc: "КЗ Рефлексов цели.",
      },
      {
        slug: "force-open",
        ru: "Взломать силой",
        en: "Force Open",
        cost: "1 действие",
        traits: ["attack"],
        desc: "Выломать дверь, сундук, решётку. Без инструмента — штраф -2.",
        dc: "Простая дверь 15; прочная 20; железная 30.",
      },
      {
        slug: "grapple",
        ru: "Захват",
        en: "Grapple",
        cost: "1 действие",
        traits: ["attack"],
        desc: "Схватить цель. Успех — grabbed; критуспех — restrained. Провал — цель свободна.",
        dc: "КЗ Стойкости цели.",
      },
      {
        slug: "high-jump",
        ru: "Высокий прыжок",
        en: "High Jump",
        cost: "2 действия",
        traits: ["move"],
        desc: "Прыжок в высоту. Базово 3 фута вверх/5 в длину; при успехе — +5 футов (или +8 при критуспехе).",
        dc: "Плоский DC 30 для прибавки.",
      },
      {
        slug: "long-jump",
        ru: "Длинный прыжок",
        en: "Long Jump",
        cost: "2 действия",
        traits: ["move"],
        desc: "Разбег (Шаг) + прыжок. Макс. длина — твоя скорость.",
        dc: "DC равен длине прыжка в футах (мин. DC 10).",
      },
      {
        slug: "reposition",
        ru: "Перемещение",
        en: "Reposition",
        trained: true,
        cost: "1 действие",
        traits: ["attack"],
        desc: "Передвинуть цель на 5 футов (10 при критуспехе). Нельзя перемещать в опасность.",
        dc: "КЗ Стойкости цели.",
      },
      {
        slug: "shove",
        ru: "Толчок",
        en: "Shove",
        cost: "1 действие",
        traits: ["attack"],
        desc: "Оттолкнуть цель на 5 футов (10 при критуспехе; при критпровале сам лежит).",
        dc: "КЗ Стойкости цели.",
      },
      {
        slug: "swim",
        ru: "Плавание",
        en: "Swim",
        cost: "1 действие",
        traits: ["move"],
        desc: "Продвинуться на 5 футов в воде (10 при критуспехе). Провал — стоишь; критпровал — идёшь ко дну 10 футов.",
        dc: "Спокойная вода 10; бурная 15; штормовая 20+.",
      },
      {
        slug: "trip",
        ru: "Подсечка",
        en: "Trip",
        cost: "1 действие",
        traits: ["attack"],
        desc: "Сбить цель с ног (prone). Критуспех — +1d6 дроп-урона.",
        dc: "КЗ Рефлексов цели. Только существа не более чем на размер больше.",
      },
    ],
  },
  {
    slug: "crafting",
    ru: "Ремесло",
    en: "Crafting",
    ability: "Интеллект",
    desc: "Изготовление и починка предметов, оценка конструкции, работа в даунтайме.",
    actions: [
      RECALL_KNOWLEDGE("предметы, ловушки, конструкции, алхимию"),
      {
        slug: "repair",
        ru: "Починка",
        en: "Repair",
        cost: "10 минут",
        traits: ["manipulate"],
        desc: "Восстановить HP предмета; нужен ремкомплект. На критуспехе — двойная починка.",
        dc: "Обычно DC 15–25 в зависимости от материала/уровня предмета.",
      },
      {
        slug: "craft",
        ru: "Создание",
        en: "Craft",
        trained: true,
        cost: "≥4 дней",
        traits: ["downtime", "manipulate"],
        desc: "Изготовить предмет из формулы. Нужны материалы на половину цены; даунтайм сокращает остаток.",
        dc: "Level DC уровня предмета. Нужен ранг, указанный у предмета/формулы.",
      },
      EARN_INCOME,
      {
        slug: "identify-alchemy",
        ru: "Определить алхимию",
        en: "Identify Alchemy",
        trained: true,
        cost: "10 минут",
        traits: ["concentrate", "manipulate", "secret"],
        desc: "Выяснить, что за алхимический предмет.",
        dc: "Level DC предмета.",
      },
    ],
  },
  {
    slug: "deception",
    ru: "Обман",
    en: "Deception",
    ability: "Харизма",
    desc: "Ложь, маскировка, сбивание с толку в бою и на разведке.",
    actions: [
      {
        slug: "create-diversion",
        ru: "Создать отвлечение",
        en: "Create a Diversion",
        cost: "1 действие",
        traits: ["mental"],
        desc: "Жест, нарочитая реплика или ловкий трюк. Успех — ты off-guard для всех, кого обманул, до конца своего хода (для Hide/Sneak).",
        dc: "Perception DC каждого наблюдателя. Повтор против того же НПЦ в сцене даёт -5.",
      },
      {
        slug: "impersonate",
        ru: "Выдавать себя",
        en: "Impersonate",
        cost: "варьируется",
        traits: ["concentrate", "manipulate", "secret"],
        desc: "Принять вид/роль другого. Обычно без броска; бросок только если кто-то подозревает.",
        dc: "Perception DC подозревающего. Против того, кто знает объект, — Society/Perception DC знающего +2.",
      },
      {
        slug: "lie",
        ru: "Солгать",
        en: "Lie",
        cost: "≥1 раунда",
        traits: ["auditory", "concentrate", "linguistic", "mental", "secret"],
        desc: "Склонить собеседника поверить в неправду. Неправдоподобность — +2…+5 к DC; полный абсурд — нельзя.",
        dc: "Perception DC цели. Союзники против общей лжи — скрытно.",
      },
      {
        slug: "feint",
        ru: "Финт",
        en: "Feint",
        trained: true,
        cost: "1 действие",
        traits: ["mental"],
        desc: "Сбить с толку противника в ближнем бою. Успех — цель off-guard для твоей следующей атаки; критуспех — до конца хода.",
        dc: "Perception DC цели. Только в пределах ближнего боя.",
      },
    ],
  },
  {
    slug: "diplomacy",
    ru: "Дипломатия",
    en: "Diplomacy",
    ability: "Харизма",
    desc: "Переговоры, улучшение отношений, сбор информации в социальной обстановке.",
    actions: [
      {
        slug: "gather-information",
        ru: "Собрать информацию",
        en: "Gather Information",
        cost: "≥2 часов",
        traits: ["exploration", "secret"],
        desc: "Походить по городу/таверне, разузнать слухи. Затраты золота — +2 к результату/дают подсказки.",
        dc: "По ситуации; обычно простое DC по рангу (15–30). Малоизвестная тема — +2/+5.",
      },
      {
        slug: "make-impression",
        ru: "Произвести впечатление",
        en: "Make an Impression",
        cost: "≥10 минут",
        traits: ["auditory", "concentrate", "linguistic", "mental"],
        desc: "Улучшить отношение НПЦ на одну ступень (критуспех — на две; критпровал — на одну в минус).",
        dc: "Will DC цели. Разница культуры/языка/предубеждения — +2…+5.",
      },
      {
        slug: "request",
        ru: "Просьба",
        en: "Request",
        cost: "1 минута",
        traits: ["auditory", "concentrate", "linguistic", "mental"],
        desc: "Попросить у НПЦ конкретную услугу. Чем больше просишь — тем выше DC.",
        dc: "GM ставит DC: friendly 15, indifferent 20, helpful 10; тяжёлая просьба +2/+5/+10.",
      },
    ],
  },
  {
    slug: "intimidation",
    ru: "Запугивание",
    en: "Intimidation",
    ability: "Харизма",
    desc: "Давление, угрозы, деморализация в бою и вне боя.",
    actions: [
      {
        slug: "coerce",
        ru: "Принудить",
        en: "Coerce",
        cost: "1 минута",
        traits: ["auditory", "concentrate", "emotion", "linguistic", "mental"],
        desc: "Заставить НПЦ выполнить просьбу под угрозой. Работает 1d6 часов; потом враждебность. Критпровал — не сработает в этой сцене.",
        dc: "Will DC цели. Существо, не боящееся урона/смерти, — невосприимчиво.",
      },
      {
        slug: "demoralize",
        ru: "Деморализовать",
        en: "Demoralize",
        cost: "1 действие",
        traits: ["auditory", "concentrate", "emotion", "fear", "mental"],
        desc: "Наложить frightened 1 (frightened 2 при критуспехе). Одна цель иммунна к повтору от тебя 10 минут.",
        dc: "Will DC цели. -4 если нет общего языка.",
      },
    ],
  },
  {
    slug: "lore",
    ru: "Знание",
    en: "Lore",
    ability: "Интеллект",
    desc: "Узкоспециализированные знания (выбирается подвид: напр., Пиратское Lore, Legal Lore, Underworld Lore).",
    actions: [
      RECALL_KNOWLEDGE("выбранную узкую тему вашего Lore"),
      EARN_INCOME,
    ],
  },
  {
    slug: "medicine",
    ru: "Медицина",
    en: "Medicine",
    ability: "Мудрость",
    desc: "Первая помощь, лечение ран, борьба с болезнями и ядами.",
    actions: [
      {
        slug: "administer-first-aid",
        ru: "Оказать первую помощь",
        en: "Administer First Aid",
        cost: "2 действия",
        traits: ["manipulate"],
        desc: "Stabilize умирающего ИЛИ остановить persistent bleed. Цель — смежная; нужны руки.",
        dc: "DC 5 для обеих версий. Критпровал — цель получает 1d8 урона.",
      },
      {
        slug: "treat-disease",
        ru: "Лечить болезнь",
        en: "Treat Disease",
        trained: true,
        cost: "8 часов",
        traits: ["downtime", "healing", "manipulate"],
        desc: "Даёшь цели бонус к спасброскам против болезни (или новый спас при критуспехе).",
        dc: "DC самой болезни (указан в описании эффекта).",
      },
      {
        slug: "treat-poison",
        ru: "Лечить яд",
        en: "Treat Poison",
        trained: true,
        cost: "1 действие",
        traits: ["healing", "manipulate"],
        desc: "Даёшь цели бонус к следующему спасу против яда (критуспех — новый спас).",
        dc: "DC самого яда.",
      },
      {
        slug: "treat-wounds",
        ru: "Лечить раны",
        en: "Treat Wounds",
        trained: true,
        cost: "10 минут",
        traits: ["healing", "manipulate"],
        desc: "Восстановить HP. После использования цель получает immunity на 1 час (Continual Recovery снимает).",
        dc: "DC 15: 2d8; DC 20 (эксперт): +10 HP и 4d8; DC 30 (мастер): +20 и 6d8; DC 40 (легендарный): +30 и 8d8.",
      },
    ],
  },
  {
    slug: "nature",
    ru: "Природа",
    en: "Nature",
    ability: "Мудрость",
    desc: "Первобытные (primal) знания: животные, растения, стихии, погода, фейри.",
    actions: [
      RECALL_KNOWLEDGE("природу, животных, стихии, фейри"),
      {
        slug: "command-animal",
        ru: "Командовать животным",
        en: "Command an Animal",
        cost: "1 действие",
        traits: ["auditory", "concentrate"],
        desc: "Отдать обученному/прирученному животному простой приказ на 1 действие (сложный — на 2).",
        dc: "Will DC животного. Невыполнимые/опасные приказы — нельзя.",
      },
      IDENTIFY_MAGIC("природного/первобытного"),
      LEARN_A_SPELL("первобытное"),
    ],
  },
  {
    slug: "occultism",
    ru: "Оккультизм",
    en: "Occultism",
    ability: "Интеллект",
    desc: "Оккультные знания: аберрации, нежить, эзотерика, духи, загадки бытия.",
    actions: [
      RECALL_KNOWLEDGE("аберрации, нежить, эзотерику, духов"),
      DECIPHER_WRITING("оккультный или эзотерический"),
      IDENTIFY_MAGIC("оккультного"),
      LEARN_A_SPELL("оккультное"),
    ],
  },
  {
    slug: "performance",
    ru: "Выступление",
    en: "Performance",
    ability: "Харизма",
    desc: "Публичные выступления: музыка, ораторство, актёрство, танец.",
    actions: [
      {
        slug: "perform",
        ru: "Выступать",
        en: "Perform",
        cost: "варьируется",
        traits: ["concentrate"],
        desc: "Публичное выступление. Используется также как база для бардовских умений и общения через искусство.",
        dc: "Простое DC по рангу или Will DC слушателей. Враждебная публика — «сложное»/«очень сложное».",
      },
      EARN_INCOME,
    ],
  },
  {
    slug: "religion",
    ru: "Религия",
    en: "Religion",
    ability: "Мудрость",
    desc: "Божественные (divine) знания: боги, обряды, нежить, небесные/дьявольские существа.",
    actions: [
      RECALL_KNOWLEDGE("богов, обряды, нежить, небесных и дьявольских существ"),
      DECIPHER_WRITING("религиозный или ритуальный"),
      IDENTIFY_MAGIC("божественного"),
      LEARN_A_SPELL("божественное"),
    ],
  },
  {
    slug: "society",
    ru: "Общество",
    en: "Society",
    ability: "Интеллект",
    desc: "Знания о людях, истории, законах, языках и письменности.",
    actions: [
      RECALL_KNOWLEDGE("историю, культуры, языки, генеалогии"),
      {
        slug: "subsist",
        ru: "Существовать",
        en: "Subsist",
        cost: "простой (сутки)",
        traits: ["downtime"],
        desc: "Выжить в городе: попрошайничество, работа за еду, приют. Успех — минимум; критуспех — скромный уют.",
        dc: "Level DC поселения/региона. Трущобы +2; враждебный город +5.",
      },
      {
        slug: "create-forgery",
        ru: "Создать подделку",
        en: "Create Forgery",
        trained: true,
        cost: "1 день",
        traits: ["downtime", "secret"],
        desc: "Изготовить поддельный документ. Проверка скрытная — ты узнаёшь результат только когда её проверят.",
        dc: "Perception DC проверяющего +2 (или +5 для знающего оригинал). Без образца — очень сложное.",
      },
      DECIPHER_WRITING("мирской, старый или кодированный"),
    ],
  },
  {
    slug: "stealth",
    ru: "Скрытность",
    en: "Stealth",
    ability: "Ловкость",
    desc: "Маскировка, скрытное перемещение, сокрытие предметов.",
    actions: [
      {
        slug: "conceal-object",
        ru: "Спрятать предмет",
        en: "Conceal an Object",
        trained: true,
        cost: "1 действие",
        traits: ["manipulate", "secret"],
        desc: "Спрятать предмет при себе (до Bulk L). Проверка обыскивающего — секретная.",
        dc: "Perception DC обыскивающего.",
      },
      {
        slug: "hide",
        ru: "Спрятаться",
        en: "Hide",
        cost: "1 действие",
        traits: ["secret"],
        desc: "Стать hidden, если у тебя есть cover или concealment. Остаёшься hidden, пока не сдвинешься/не атакуешь.",
        dc: "Perception DC каждого врага.",
      },
      {
        slug: "sneak",
        ru: "Красться",
        en: "Sneak",
        cost: "1 действие",
        traits: ["move", "secret"],
        desc: "Двигаться до Скорости, оставаясь hidden/undetected. В конце движения должен быть cover/concealment.",
        dc: "Perception DC каждого врага.",
      },
    ],
  },
  {
    slug: "survival",
    ru: "Выживание",
    en: "Survival",
    ability: "Мудрость",
    desc: "Ориентирование, выживание в дикой природе, следопытство.",
    actions: [
      {
        slug: "sense-direction",
        ru: "Определить направление",
        en: "Sense Direction",
        cost: "1 минута",
        traits: ["exploration"],
        desc: "Понять, где стороны света, и найти путь в знакомой местности.",
        dc: "Знакомая местность 15; незнакомая 20; под землёй/в тумане +2…+5.",
      },
      {
        slug: "subsist",
        ru: "Существовать",
        en: "Subsist",
        cost: "простой (сутки)",
        traits: ["downtime"],
        desc: "Добыть пищу и укрытие в глуши на себя и близких. Критуспех — комфорт плюс.",
        dc: "Лес/степь 10; пустыня/тундра 20; экзотика 25+.",
      },
      {
        slug: "cover-tracks",
        ru: "Замести следы",
        en: "Cover Tracks",
        trained: true,
        cost: "исследование",
        traits: ["exploration"],
        desc: "Идёшь вполовину скорости, усложняешь преследование.",
        dc: "Твой результат задаёт DC преследователю (вместо обычного).",
      },
      {
        slug: "track",
        ru: "Выследить",
        en: "Track",
        trained: true,
        cost: "исследование",
        traits: ["concentrate", "move"],
        desc: "Идти по следу вполовину скорости. Проверка раз в час (в сложных условиях — чаще).",
        dc: "Мягкая земля 15; твёрдая 20; камень/вода +5. Свежие следы -2; старые сутки+ — +2…+5.",
      },
    ],
  },
  {
    slug: "thievery",
    ru: "Воровство",
    en: "Thievery",
    ability: "Ловкость",
    desc: "Ловкость рук, замки, ловушки, карманные кражи.",
    actions: [
      {
        slug: "disable-device",
        ru: "Вывести устройство из строя",
        en: "Disable a Device",
        trained: true,
        cost: "2 действия",
        traits: ["manipulate"],
        desc: "Обезвредить ловушку или простое устройство. Сложные требуют нескольких успехов подряд.",
        dc: "Level DC ловушки/устройства. Без воровских инструментов — -2 или невозможно.",
      },
      {
        slug: "palm-object",
        ru: "Стащить предмет",
        en: "Palm an Object",
        cost: "1 действие",
        traits: ["manipulate"],
        desc: "Незаметно взять лежащий невзятый предмет (Bulk L или меньше).",
        dc: "Perception DC наблюдателя.",
      },
      {
        slug: "pick-a-lock",
        ru: "Вскрыть замок",
        en: "Pick a Lock",
        trained: true,
        cost: "2 действия",
        traits: ["manipulate"],
        desc: "Открыть замок. Сложные — несколько успехов (обычно 2).",
        dc: "Простой 15; средний 20; хороший 25; великолепный 30. Без инструментов — штраф/нельзя.",
      },
      {
        slug: "steal",
        ru: "Украсть",
        en: "Steal",
        cost: "1 действие",
        traits: ["manipulate"],
        desc: "Срезать кошелёк, вытащить предмет из сумки. Только небольшие, незакреплённые вещи.",
        dc: "Perception DC цели. Предмет в руках/активно контролируемый — обычно нельзя (или +5).",
      },
    ],
  },
];

export const SKILL_BY_SLUG: Record<string, SkillDef> = Object.fromEntries(
  SKILLS.map((s) => [s.slug, s]),
);
